### ISSUE TITLE
Update Background Color for Staff Member Cards "about" page

### ISSUE THREAD

**Issue by T0nj3** [NoroffFEU/musikkforandrerliv.no#601]
- [x] Change the HEX color #D9D9D9 in the HTML to #FBF7E8 to match the Figma design for the staff member cards. **The colors should be in tailwind, we will not use hex color, so you have to add it to tailwind and if it is not there, add it **

- [x] Ensure the new color is applied consistently across all staff member cards.

![Image](https://github.com/user-attachments/assets/ef68ea27-2768-433d-b466-43c8419808f6)

**Comment by stineknutsen** [comment]
Just to make sure:
This is a color we're adding that is supposed to be different from the rest?
I'm asking because the color from the styleguide with the hex code #F8EED1 is used in the other pages of the website and already saved in tailwind as ivory beige. They are quite similar so I just want to make sure.

**Comment by T0nj3** [comment]
If i understand you correctly then my answer is YES, use that color in tailwind if that is the right one. If it is the right one just change it from hex in the html to the tailwind-color.
