### ISSUE TITLE
 Review Design Wireframe: Our work Page

### ISSUE THREAD

**Issue by lem31** [NoroffFEU/musikkforandrerliv.no#92]
- [x] Visual Hierarchy
- [x] Layout
- [x] Consistency
- [x] Screen size
- [x] Usability Principles
- [x] Web Content Accessibility Guidelines (WCAG)
- [x] Colors
- [x] Fonts
- [x] Whitespace and padding
- [x] Image quality
- [x] Iconography
- [x] Micro interactions
- [x] Error states and feedback
- [x] Performance Optimization
- [x] Design documentation

See Design wireframe/prototype checklist for more info

**Comment by Oyvindeavor** [comment]
### Desktop 
- I noticed the space between the footer and the newsletter element is inconsistent across all the pages in the wireframe.
<img width="932" alt="Screenshot 2024-04-08 at 18 30 34" src="https://github.com/NoroffFEU/musikkforandrerliv.no/assets/133252875/655a456c-a416-4c9f-a108-99ecf356daaa">

### Mobile
-  All the paragraph texts has "poppins" font while in the styleguide it is specified to use monsterrat.
<img width="1061" alt="Screenshot 2024-04-08 at 18 28 03" src="https://github.com/NoroffFEU/musikkforandrerliv.no/assets/133252875/4ba9cb3c-45fa-4530-a0ac-67b65fb5fe11">

**Comment by Vickabu** [comment]
This is taken from the "on hold" section and not from the "Testing QA feedback" section. Newsletter are as mentioned in other issues being worked on. The text poppins is not being used in the card, it was a placeholder for a short time when finishing the libary. Closing this issue since newsletter is in other issues.
